# Weekly Report Handler for Owner Commands

from telegram import Update
from telegram.ext import ContextTypes, CommandHandler, MessageHandler, filters
import bot.db as db
from bot.utils import restricted
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

@restricted(allowed_roles=['owner'])
async def show_weekly_report(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show weekly report for owner."""
    try:
        await update.message.reply_text("📊 Generating weekly report... Please wait.")
        
        # Generate report
        report = db.generate_weekly_report()
        
        if len(report) <= 4096:
            await update.message.reply_text(report, parse_mode='HTML')
        else:
            # Split the report into chunks
            chunks = [report[i:i+4000] for i in range(0, len(report), 4000)]
            for i, chunk in enumerate(chunks):
                if i == 0:
                    await update.message.reply_text(f"📊 Weekly Report Part {i+1}/{len(chunks)}\n\n{chunk}", parse_mode='HTML')
                else:
                    await update.message.reply_text(f"📊 Part {i+1}/{len(chunks)}\n\n{chunk}", parse_mode='HTML')
        
        logger.info(f"Weekly report generated by Owner")
        
    except Exception as e:
        logger.error(f"Error generating weekly report: {e}")
        await update.message.reply_text(f"❌ Error generating weekly report: {str(e)}")

# Handler list for registration
weekly_handlers = [
    CommandHandler('weeklyreport', show_weekly_report),
    MessageHandler(filters.Regex("^📊 Weekly Report$"), show_weekly_report),
]